# Generated by Django 2.2.3 on 2020-03-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
